### ISSUE TITLE
Syntax highlighting issue when there is no space preceding <

### ISSUE THREAD

**Issue by hoanhtien** [Microsoft/TypeScript-Sublime-Plugin#285]
Related to https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/265.

Issue:
![image](https://cloud.githubusercontent.com/assets/1707813/8627292/da8f8be4-26fe-11e5-97ce-2b2a8b257afa.png)

Correct:
![image](https://cloud.githubusercontent.com/assets/1707813/8627340/3e27dbf2-26ff-11e5-8751-7e8576cbd230.png)

**Comment by hoanhtien** [comment]
To deal with cases like `foo<A>()`, we have the following rule "when an identifier followed by a less-than sign, parse it as a function name":

```
  type-parameters:
    name: meta.type.parameters.ts
    begin: '([a-zA-Z_$][\w$]*)?(<)'            # identifier followed by a less-than sign
    beginCaptures:
      '1': { name: entity.name.type.ts }       # parse the identifier as function name
      '2': { name: meta.brace.angle.ts }       
    end: '(?=$)|(>)'                                  
    endCaptures:
      '2': { name: meta.brace.angle.ts }
    patterns:
    - name: keyword.other.ts
      match: '\b(extends)\b'
    - include: '#comment'
    - include: '#type'
```

However this rule does not work with less-than conditions like `foo<A`, or `i<10` in the screenshot above.

I have not found a good way to address this problem. Any thought @billti @zhengbli?
