### ISSUE TITLE
Plugin slows down Sublime Text

### ISSUE THREAD

**Issue by Serega124** [Microsoft/TypeScript-Sublime-Plugin#716]
Typescript plugin extremely slows down text typing and selection performance on large files like [tsserver.js](https://github.com/Microsoft/TypeScript/blob/master/lib/tsserver.js). Slowing down appears even after renaming that file to .txt and opening as Plain Text. This is very annoying when you need to view large logs or csv files.

This behavior is reproducible in clean portable installation of Sublime Text with only TypeScript plugin installed even without opened project and `tsconfig.json`.

Disabling plugin via Package Control makes Sublime smooth again. Can using [*_async api](http://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener) help here? Or is there any setting to disable processing non-js/ts files?

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 x 3000)|
|Memory (System)|15.93GB (9.38GB free)|
|System|Windows 10.0.17763.475 (x64)|
|Sublime|v3.2.1 build 3207 x64 stable channel|
|Typescript plugin|v3.4.1|
</details>
<details>
<summary>Plugin Event Profile</summary>

```
This list shows how much time each plugin has taken to respond to each event:

on_activated:
    Default.pane: 0.001s total, mean: 0.000s, max: 0.001s
    TypeScript.typescript.listeners.listeners: 1.334s total, mean: 0.056s, max: 0.265s

on_close:
    Default.pane: 0.000s total, mean: 0.000s, max: 0.000s
    TypeScript.typescript.listeners.listeners: 0.164s total, mean: 0.055s, max: 0.163s

on_deactivated:
    Default.history_list: 0.011s total, mean: 0.000s, max: 0.002s

on_hover:
    Default.symbol: 0.004s total, mean: 0.000s, max: 0.001s
    TypeScript.typescript.listeners.listeners: 3.556s total, mean: 0.155s, max: 0.691s

on_load:
    Default.detect_indentation: 0.003s total, mean: 0.002s, max: 0.003s
    TypeScript.typescript.listeners.listeners: 0.000s total, mean: 0.000s, max: 0.000s
    Default.exec: 0.003s total, mean: 0.001s, max: 0.002s

on_modified:
    TypeScript.typescript.listeners.listeners: 36.134s total, mean: 0.317s, max: 1.174s

on_pre_close:
    Default.history_list: 0.000s total, mean: 0.000s, max: 0.000s

on_selection_modified:
    TypeScript.typescript.listeners.listeners: 88.955s total, mean: 0.217s, max: 1.569s
```

</details>
